// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preson.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Preson.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PresonRoot

@implementation PresonRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - PresonRoot_FileDescriptor

static GPBFileDescriptor *PresonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Preson

@implementation Preson

@dynamic name;
@dynamic uid;
@dynamic email;
@dynamic phoneArray, phoneArray_Count;

typedef struct Preson__storage_ {
  uint32_t _has_storage_[1];
  int32_t uid;
  NSString *name;
  NSString *email;
  NSMutableArray *phoneArray;
} Preson__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = Preson_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Preson__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "uid",
        .dataTypeSpecific.className = NULL,
        .number = Preson_FieldNumber_Uid,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Preson__storage_, uid),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "email",
        .dataTypeSpecific.className = NULL,
        .number = Preson_FieldNumber_Email,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Preson__storage_, email),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Preson_PhoneNumber),
        .number = Preson_FieldNumber_PhoneArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(Preson__storage_, phoneArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Preson class]
                                     rootClass:[PresonRoot class]
                                          file:PresonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Preson__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum Preson_PhoneType

GPBEnumDescriptor *Preson_PhoneType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Mobile\000Home\000Work\000";
    static const int32_t values[] = {
        Preson_PhoneType_Mobile,
        Preson_PhoneType_Home,
        Preson_PhoneType_Work,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(Preson_PhoneType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:Preson_PhoneType_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL Preson_PhoneType_IsValidValue(int32_t value__) {
  switch (value__) {
    case Preson_PhoneType_Mobile:
    case Preson_PhoneType_Home:
    case Preson_PhoneType_Work:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Preson_PhoneNumber

@implementation Preson_PhoneNumber

@dynamic number;
@dynamic phoneType;

typedef struct Preson_PhoneNumber__storage_ {
  uint32_t _has_storage_[1];
  Preson_PhoneType phoneType;
  NSString *number;
} Preson_PhoneNumber__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "number",
        .dataTypeSpecific.className = NULL,
        .number = Preson_PhoneNumber_FieldNumber_Number,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Preson_PhoneNumber__storage_, number),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "phoneType",
        .dataTypeSpecific.enumDescFunc = Preson_PhoneType_EnumDescriptor,
        .number = Preson_PhoneNumber_FieldNumber_PhoneType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Preson_PhoneNumber__storage_, phoneType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Preson_PhoneNumber class]
                                     rootClass:[PresonRoot class]
                                          file:PresonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Preson_PhoneNumber__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    [localDescriptor setupContainingMessageClassName:GPBStringifySymbol(Preson)];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t Preson_PhoneNumber_PhoneType_RawValue(Preson_PhoneNumber *message) {
  GPBDescriptor *descriptor = [Preson_PhoneNumber descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Preson_PhoneNumber_FieldNumber_PhoneType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPreson_PhoneNumber_PhoneType_RawValue(Preson_PhoneNumber *message, int32_t value) {
  GPBDescriptor *descriptor = [Preson_PhoneNumber descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:Preson_PhoneNumber_FieldNumber_PhoneType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
